export const AUDIO_LOCAL_STORAGE_KEY = 'AUDIO';
export const VIBRATION_LOCAL_STORAGE_KEY = 'VIBRATION';
export const FIRST_TAP_HELP_LOCAL_STORAGE_KEY = 'FIRST_TAP_HELP';

export const ACCESS_TOKEN_LOCAL_STORAGE_KEY = 'ACCESS_TOKEN';